export const nexoraAgentIdentityAbi = [
  {
    inputs: [{ internalType: "string", name: "metadataURI", type: "string" }],
    name: "registerAgent",
    outputs: [{ internalType: "uint256", name: "agentId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "nextAgentId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const nexoraFactoryAbi = [
  {
    inputs: [{ internalType: "uint256", name: "agentId", type: "uint256" }],
    name: "createAgentWallet",
    outputs: [{ internalType: "address", name: "wallet", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "walletOfAgent",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const nexoraSmartWalletRegistryAbi = [
  {
    inputs: [],
    name: "EmptyMetadataURI",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidMode",
    type: "error",
  },
  {
    inputs: [],
    name: "NotSmartWalletOwner",
    type: "error",
  },
  {
    inputs: [],
    name: "SmartWalletNotFound",
    type: "error",
  },
  {
    inputs: [
      { internalType: "string", name: "metadataURI", type: "string" },
      { internalType: "bytes32", name: "harnessId", type: "bytes32" },
      { internalType: "uint8", name: "riskMode", type: "uint8" },
      { internalType: "uint8", name: "runnerMode", type: "uint8" },
    ],
    name: "registerSmartWallet",
    outputs: [{ internalType: "uint256", name: "smartWalletId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "smartWalletId", type: "uint256" }],
    name: "createSmartWallet",
    outputs: [{ internalType: "address", name: "wallet", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "smartWalletId", type: "uint256" }],
    name: "getSmartWallet",
    outputs: [
      {
        components: [
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "address", name: "wallet", type: "address" },
          { internalType: "string", name: "metadataURI", type: "string" },
          { internalType: "bytes32", name: "harnessId", type: "bytes32" },
          { internalType: "uint8", name: "riskMode", type: "uint8" },
          { internalType: "uint8", name: "runnerMode", type: "uint8" },
          { internalType: "uint64", name: "createdAt", type: "uint64" },
          { internalType: "uint64", name: "walletCreatedAt", type: "uint64" },
        ],
        internalType: "struct NexoraSmartWalletRegistry.SmartWallet",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "smartWalletsOfOwner",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "smartWalletId", type: "uint256" }],
    name: "walletOfSmartWallet",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextSmartWalletId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const nexoraRiskRegistryAbi = [
  {
    inputs: [
      { internalType: "uint256", name: "agentId", type: "uint256" },
      { internalType: "bytes32", name: "harnessId", type: "bytes32" },
      { internalType: "bytes32", name: "objectiveRunId", type: "bytes32" },
      { internalType: "bytes32", name: "intentHash", type: "bytes32" },
      { internalType: "uint16", name: "riskScore", type: "uint16" },
      { internalType: "bool", name: "policyPassed", type: "bool" },
      { internalType: "uint16", name: "benchmarkScore", type: "uint16" },
      { internalType: "bytes32", name: "reportHash", type: "bytes32" },
    ],
    name: "recordReport",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export const nexoraPreflightRegistryAbi = [
  { inputs: [], name: "InvalidScore", type: "error" },
  { inputs: [], name: "MissingIntentHash", type: "error" },
  { inputs: [], name: "NotSmartWalletOwner", type: "error" },
  { inputs: [], name: "PreflightAlreadyRecorded", type: "error" },
  { inputs: [], name: "PreflightNotFound", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "walletId", type: "uint256" },
      { internalType: "uint16", name: "basicScore", type: "uint16" },
      { internalType: "uint16", name: "adversarialScore", type: "uint16" },
      { internalType: "uint16", name: "externalScore", type: "uint16" },
      { internalType: "uint16", name: "averageScore", type: "uint16" },
      { internalType: "uint16", name: "maxRiskScore", type: "uint16" },
      { internalType: "uint32", name: "freshnessSeconds", type: "uint32" },
    ],
    name: "setPreflightThresholds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "walletId", type: "uint256" }],
    name: "getPreflightThresholds",
    outputs: [
      {
        components: [
          { internalType: "uint16", name: "basicScore", type: "uint16" },
          { internalType: "uint16", name: "adversarialScore", type: "uint16" },
          { internalType: "uint16", name: "externalScore", type: "uint16" },
          { internalType: "uint16", name: "averageScore", type: "uint16" },
          { internalType: "uint16", name: "maxRiskScore", type: "uint16" },
          { internalType: "uint32", name: "freshnessSeconds", type: "uint32" },
          { internalType: "bool", name: "exists", type: "bool" },
        ],
        internalType: "struct NexoraPreflightRegistry.PreflightThresholds",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "uint256", name: "walletId", type: "uint256" },
          { internalType: "bytes32", name: "actionIntentHash", type: "bytes32" },
          { internalType: "bytes32", name: "modelHash", type: "bytes32" },
          { internalType: "bytes32", name: "harnessHash", type: "bytes32" },
          { internalType: "bytes32", name: "policyHash", type: "bytes32" },
          { internalType: "bytes32", name: "toolsHash", type: "bytes32" },
          { internalType: "bytes32", name: "suiteHash", type: "bytes32" },
          { internalType: "uint16", name: "basicScore", type: "uint16" },
          { internalType: "uint16", name: "adversarialScore", type: "uint16" },
          { internalType: "uint16", name: "externalScore", type: "uint16" },
          { internalType: "uint16", name: "averageScore", type: "uint16" },
          { internalType: "uint16", name: "maxRiskScore", type: "uint16" },
          { internalType: "bool", name: "passed", type: "bool" },
        ],
        internalType: "struct NexoraPreflightRegistry.PreflightInput",
        name: "input",
        type: "tuple",
      },
    ],
    name: "recordPreflight",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "actionIntentHash", type: "bytes32" }],
    name: "getPreflight",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "walletId", type: "uint256" },
          { internalType: "bytes32", name: "actionIntentHash", type: "bytes32" },
          { internalType: "bytes32", name: "modelHash", type: "bytes32" },
          { internalType: "bytes32", name: "harnessHash", type: "bytes32" },
          { internalType: "bytes32", name: "policyHash", type: "bytes32" },
          { internalType: "bytes32", name: "toolsHash", type: "bytes32" },
          { internalType: "bytes32", name: "suiteHash", type: "bytes32" },
          { internalType: "uint16", name: "basicScore", type: "uint16" },
          { internalType: "uint16", name: "adversarialScore", type: "uint16" },
          { internalType: "uint16", name: "externalScore", type: "uint16" },
          { internalType: "uint16", name: "averageScore", type: "uint16" },
          { internalType: "uint16", name: "maxRiskScore", type: "uint16" },
          { internalType: "bool", name: "passed", type: "bool" },
          { internalType: "uint256", name: "timestamp", type: "uint256" },
          { internalType: "address", name: "reporter", type: "address" },
        ],
        internalType: "struct NexoraPreflightRegistry.PreflightRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const nexoraAgentWalletAbi = [
  { inputs: [], name: "ExecutionFailed", type: "error" },
  { inputs: [], name: "IntentMismatch", type: "error" },
  { inputs: [], name: "MissingReport", type: "error" },
  { inputs: [], name: "NotOwner", type: "error" },
  { inputs: [], name: "PolicyBlockedExecution", type: "error" },
  { inputs: [], name: "PreflightFailed", type: "error" },
  { inputs: [], name: "PreflightScoreTooLow", type: "error" },
  { inputs: [], name: "PreflightStale", type: "error" },
  { inputs: [], name: "PreflightWalletMismatch", type: "error" },
  { inputs: [], name: "RiskTooHigh", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "target", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
      { internalType: "bytes", name: "data", type: "bytes" },
      { internalType: "bytes32", name: "intentHash", type: "bytes32" },
      { internalType: "uint16", name: "maxRiskScore", type: "uint16" },
      {
        components: [
          { internalType: "bytes32", name: "intentHash", type: "bytes32" },
          { internalType: "uint16", name: "riskScore", type: "uint16" },
          { internalType: "bool", name: "policyPassed", type: "bool" },
          { internalType: "bytes32", name: "reportHash", type: "bytes32" },
        ],
        internalType: "struct NexoraAgentWallet.ExecutionReport",
        name: "report",
        type: "tuple",
      },
    ],
    name: "executeWithRiskReport",
    outputs: [{ internalType: "bytes", name: "result", type: "bytes" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "preflightRegistry", type: "address" },
      { internalType: "address", name: "target", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
      { internalType: "bytes", name: "data", type: "bytes" },
      { internalType: "bytes32", name: "actionIntentHash", type: "bytes32" },
      { internalType: "uint16", name: "riskScore", type: "uint16" },
    ],
    name: "executeWithPreflight",
    outputs: [{ internalType: "bytes", name: "result", type: "bytes" }],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export const nexoraReputationAbi = [
  {
    inputs: [
      { internalType: "uint256", name: "agentId", type: "uint256" },
      { internalType: "bool", name: "executed", type: "bool" },
      { internalType: "bool", name: "policyViolation", type: "bool" },
      { internalType: "uint16", name: "riskScore", type: "uint16" },
      { internalType: "uint16", name: "benchmarkScore", type: "uint16" },
    ],
    name: "recordRun",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agentId", type: "uint256" }],
    name: "getStats",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "benchmarkRuns", type: "uint256" },
          { internalType: "uint256", name: "safeActions", type: "uint256" },
          { internalType: "uint256", name: "blockedActions", type: "uint256" },
          { internalType: "uint256", name: "policyViolations", type: "uint256" },
          { internalType: "uint256", name: "totalRiskScore", type: "uint256" },
          { internalType: "uint256", name: "totalBenchmarkScore", type: "uint256" },
          { internalType: "uint256", name: "trustScore", type: "uint256" },
        ],
        internalType: "struct NexoraReputation.Stats",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const nexoraAgentIdentityRegistryAbi = [
  {
    inputs: [{ internalType: "string", name: "agentURI", type: "string" }],
    name: "registerAgent",
    outputs: [{ internalType: "uint256", name: "agentId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agentId", type: "uint256" }],
    name: "getAgent",
    outputs: [
      {
        components: [
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "string", name: "agentURI", type: "string" },
          { internalType: "address", name: "agentWallet", type: "address" },
          { internalType: "uint64", name: "createdAt", type: "uint64" },
        ],
        internalType: "struct NexoraAgentIdentityRegistry.Agent",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "agentsOfOwner",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agentId", type: "uint256" }],
    name: "agentWalletOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextAgentId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const nexora4337WalletFactoryAbi = [
  {
    inputs: [
      { internalType: "string", name: "agentURI", type: "string" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
    ],
    name: "createAgentWallet",
    outputs: [
      { internalType: "uint256", name: "agentId", type: "uint256" },
      { internalType: "address", name: "wallet", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "walletOfAgent",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const nexoraAgentValidationRegistryAbi = [
  { inputs: [], name: "InvalidScore", type: "error" },
  { inputs: [], name: "MissingIntentHash", type: "error" },
  { inputs: [], name: "NotAuthorizedReporter", type: "error" },
  { inputs: [], name: "NotAgentOwner", type: "error" },
  { inputs: [], name: "ValidationAlreadyRecorded", type: "error" },
  { inputs: [], name: "ValidationNotFound", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "authorizedReporters",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "agentId", type: "uint256" },
      { internalType: "address", name: "reporter", type: "address" },
      { internalType: "bool", name: "enabled", type: "bool" },
    ],
    name: "setReporter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "agentId", type: "uint256" },
      { internalType: "uint16", name: "basicScore", type: "uint16" },
      { internalType: "uint16", name: "adversarialScore", type: "uint16" },
      { internalType: "uint16", name: "externalScore", type: "uint16" },
      { internalType: "uint16", name: "averageScore", type: "uint16" },
      { internalType: "uint16", name: "maxRiskScore", type: "uint16" },
      { internalType: "uint32", name: "freshnessSeconds", type: "uint32" },
    ],
    name: "setThresholds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agentId", type: "uint256" }],
    name: "getThresholds",
    outputs: [
      {
        components: [
          { internalType: "uint16", name: "basicScore", type: "uint16" },
          { internalType: "uint16", name: "adversarialScore", type: "uint16" },
          { internalType: "uint16", name: "externalScore", type: "uint16" },
          { internalType: "uint16", name: "averageScore", type: "uint16" },
          { internalType: "uint16", name: "maxRiskScore", type: "uint16" },
          { internalType: "uint32", name: "freshnessSeconds", type: "uint32" },
          { internalType: "bool", name: "exists", type: "bool" },
        ],
        internalType: "struct NexoraAgentValidationRegistry.Thresholds",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "uint256", name: "agentId", type: "uint256" },
          { internalType: "bytes32", name: "actionIntentHash", type: "bytes32" },
          { internalType: "bytes32", name: "modelHash", type: "bytes32" },
          { internalType: "bytes32", name: "harnessHash", type: "bytes32" },
          { internalType: "bytes32", name: "policyHash", type: "bytes32" },
          { internalType: "bytes32", name: "toolsHash", type: "bytes32" },
          { internalType: "bytes32", name: "suiteHash", type: "bytes32" },
          { internalType: "bytes32", name: "reportHash", type: "bytes32" },
          { internalType: "uint16", name: "basicScore", type: "uint16" },
          { internalType: "uint16", name: "adversarialScore", type: "uint16" },
          { internalType: "uint16", name: "externalScore", type: "uint16" },
          { internalType: "uint16", name: "averageScore", type: "uint16" },
          { internalType: "uint16", name: "maxRiskScore", type: "uint16" },
          { internalType: "bool", name: "passed", type: "bool" },
        ],
        internalType: "struct NexoraAgentValidationRegistry.ValidationInput",
        name: "input",
        type: "tuple",
      },
    ],
    name: "recordValidation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "target", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
      { internalType: "bytes", name: "data", type: "bytes" },
      { internalType: "bytes32", name: "actionIntentHash", type: "bytes32" },
      { internalType: "uint16", name: "riskScore", type: "uint16" },
    ],
    name: "executeWithPreflight",
    outputs: [{ internalType: "bytes", name: "result", type: "bytes" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "agentId", type: "uint256" },
      { indexed: true, internalType: "bytes32", name: "actionIntentHash", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "reportHash", type: "bytes32" },
      { indexed: false, internalType: "uint16", name: "averageScore", type: "uint16" },
      { indexed: false, internalType: "bool", name: "passed", type: "bool" },
      { indexed: false, internalType: "address", name: "reporter", type: "address" },
    ],
    name: "ValidationRecorded",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint256", name: "agentId", type: "uint256" }],
    name: "validationsOfAgent",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agentId", type: "uint256" }],
    name: "getAgentValidations",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "actionIntentHash", type: "bytes32" }],
    name: "getValidation",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "agentId", type: "uint256" },
          { internalType: "bytes32", name: "actionIntentHash", type: "bytes32" },
          { internalType: "bytes32", name: "modelHash", type: "bytes32" },
          { internalType: "bytes32", name: "harnessHash", type: "bytes32" },
          { internalType: "bytes32", name: "policyHash", type: "bytes32" },
          { internalType: "bytes32", name: "toolsHash", type: "bytes32" },
          { internalType: "bytes32", name: "suiteHash", type: "bytes32" },
          { internalType: "bytes32", name: "reportHash", type: "bytes32" },
          { internalType: "uint16", name: "basicScore", type: "uint16" },
          { internalType: "uint16", name: "adversarialScore", type: "uint16" },
          { internalType: "uint16", name: "externalScore", type: "uint16" },
          { internalType: "uint16", name: "averageScore", type: "uint16" },
          { internalType: "uint16", name: "maxRiskScore", type: "uint16" },
          { internalType: "bool", name: "passed", type: "bool" },
          { internalType: "uint256", name: "timestamp", type: "uint256" },
          { internalType: "address", name: "reporter", type: "address" },
        ],
        internalType: "struct NexoraAgentValidationRegistry.ValidationRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const nexora4337AgentWalletAbi = [
  { inputs: [], name: "ExecutionFailed", type: "error" },
  { inputs: [], name: "IntentAlreadyConsumed", type: "error" },
  { inputs: [], name: "InvalidNonce", type: "error" },
  { inputs: [], name: "InvalidUserOperation", type: "error" },
  { inputs: [], name: "InvalidValidationRegistry", type: "error" },
  { inputs: [], name: "NoEntryPoint", type: "error" },
  { inputs: [], name: "NotAuthorized", type: "error" },
  { inputs: [], name: "PreflightFailed", type: "error" },
  { inputs: [], name: "PreflightScoreTooLow", type: "error" },
  { inputs: [], name: "PreflightStale", type: "error" },
  { inputs: [], name: "PreflightWalletMismatch", type: "error" },
  { inputs: [], name: "RiskTooHigh", type: "error" },
  { inputs: [], name: "SpendLimitExceeded", type: "error" },
  { inputs: [], name: "SelectorNotAllowed", type: "error" },
  { inputs: [], name: "TargetNotAllowed", type: "error" },
  {
    inputs: [],
    name: "executorPolicy",
    outputs: [
      { internalType: "address", name: "executor", type: "address" },
      { internalType: "bool", name: "enabled", type: "bool" },
      { internalType: "bool", name: "requirePreflight", type: "bool" },
      { internalType: "uint256", name: "maxValuePerAction", type: "uint256" },
      { internalType: "uint256", name: "dailyLimit", type: "uint256" },
      { internalType: "uint64", name: "validUntil", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "allowedTargets",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllowedTargets",
    outputs: [
      { internalType: "address[]", name: "targets", type: "address[]" },
      { internalType: "bool[]", name: "allowedStatuses", type: "bool[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "bytes4", name: "", type: "bytes4" },
    ],
    name: "allowedTargetSelectors",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "day", type: "uint256" }],
    name: "spentByDay",
    outputs: [{ internalType: "uint256", name: "spent", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "executor", type: "address" },
      { internalType: "bool", name: "enabled", type: "bool" },
      { internalType: "bool", name: "requirePreflight", type: "bool" },
      { internalType: "uint256", name: "maxValuePerAction", type: "uint256" },
      { internalType: "uint256", name: "dailyLimit", type: "uint256" },
      { internalType: "uint64", name: "validUntil", type: "uint64" },
    ],
    name: "setExecutorPolicy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "target", type: "address" },
      { internalType: "bool", name: "allowed", type: "bool" },
    ],
    name: "setAllowedTarget",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "target", type: "address" },
      { internalType: "bytes4", name: "selector", type: "bytes4" },
      { internalType: "bool", name: "allowed", type: "bool" },
    ],
    name: "setAllowedSelector",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "validationRegistry",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "entryPointDeposit",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "hash", type: "bytes32" },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "isValidSignature",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "target", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
      { internalType: "bytes", name: "data", type: "bytes" },
      { internalType: "bytes32", name: "actionIntentHash", type: "bytes32" },
      { internalType: "uint16", name: "riskScore", type: "uint16" },
    ],
    name: "executeWithPreflightByExecutor",
    outputs: [{ internalType: "bytes", name: "result", type: "bytes" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "actionIntentHash", type: "bytes32" },
    ],
    name: "ActionIntentConsumed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "target", type: "address" },
      { indexed: false, internalType: "uint256", name: "value", type: "uint256" },
      { indexed: false, internalType: "bytes", name: "data", type: "bytes" },
      { indexed: false, internalType: "bytes", name: "result", type: "bytes" },
    ],
    name: "Executed",
    type: "event",
  },
] as const;

export const nexoraBenchmarkVaultAbi = [
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const nexoraBenchmarkRegistryAbi = [
  { inputs: [], name: "BenchmarkNotFound", type: "error" },
  { inputs: [], name: "EmptyBenchmarkData", type: "error" },
  { inputs: [], name: "EmptyBenchmarkHash", type: "error" },
  { inputs: [], name: "EmptyBenchmarkName", type: "error" },
  { inputs: [], name: "InactiveBenchmark", type: "error" },
  { inputs: [], name: "NotAgentOwner", type: "error" },
  { inputs: [], name: "NotBenchmarkOwner", type: "error" },
  {
    inputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "description", type: "string" },
      { internalType: "string", name: "benchmarkType", type: "string" },
      { internalType: "string", name: "benchmarkDataJson", type: "string" },
      { internalType: "address[]", name: "targetContracts", type: "address[]" },
      { internalType: "uint8", name: "riskMode", type: "uint8" },
      { internalType: "bytes32", name: "benchmarkHash", type: "bytes32" },
    ],
    name: "registerBenchmark",
    outputs: [{ internalType: "uint256", name: "benchmarkId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "agentId", type: "uint256" },
      { internalType: "uint256", name: "benchmarkId", type: "uint256" },
    ],
    name: "selectBenchmarkForAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "benchmarksOfOwner",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agentId", type: "uint256" }],
    name: "activeBenchmarkOfAgent",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "benchmarkId", type: "uint256" }],
    name: "getBenchmark",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "benchmarkId", type: "uint256" },
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "string", name: "name", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "string", name: "benchmarkType", type: "string" },
          { internalType: "string", name: "benchmarkDataJson", type: "string" },
          { internalType: "address[]", name: "targetContracts", type: "address[]" },
          { internalType: "bytes32", name: "benchmarkHash", type: "bytes32" },
          { internalType: "uint8", name: "riskMode", type: "uint8" },
          { internalType: "bool", name: "active", type: "bool" },
          { internalType: "uint64", name: "createdAt", type: "uint64" },
        ],
        internalType: "struct NexoraBenchmarkRegistry.Benchmark",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const nexoraAgentReputationRegistryAbi = [
  {
    inputs: [{ internalType: "uint256", name: "agentId", type: "uint256" }],
    name: "getReputation",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "benchmarkRuns", type: "uint256" },
          { internalType: "uint256", name: "safeExecutions", type: "uint256" },
          { internalType: "uint256", name: "blockedExecutions", type: "uint256" },
          { internalType: "uint256", name: "policyViolations", type: "uint256" },
          { internalType: "uint256", name: "totalRiskScore", type: "uint256" },
          { internalType: "uint256", name: "totalBenchmarkScore", type: "uint256" },
          { internalType: "uint256", name: "trustScore", type: "uint256" },
        ],
        internalType: "struct NexoraAgentReputationRegistry.Reputation",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const nexoraBenchmarkDexAbi = [
  {
    inputs: [],
    name: "reserves",
    outputs: [
      { internalType: "uint256", name: "mntReserve", type: "uint256" },
      { internalType: "uint256", name: "tokenReserve", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "mntIn", type: "uint256" }],
    name: "quoteMntForTokens",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenIn", type: "uint256" }],
    name: "quoteTokensForMnt",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "minTokenOut", type: "uint256" }],
    name: "swapMntForTokens",
    outputs: [{ internalType: "uint256", name: "tokenOut", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
] as const;
